{% extends "../../core/templates/materialCard.swig" %}

{% block content-container %}
	<div class="list-group">
		<div class="list-group-item media hidden-xs">
			<div class="row media-body media-sides-padding-right">
				<div class="col-sm-4">
					<span class="f-700">NOMBRE</span>
				</div>
			</div>
		</div>
	</div>

	<div class="collection-main list-group lg-odd-black"></div>

	<div class="pagination-region clearfix"></div>
{% endblock %}
